### ISSUE TITLE
behind reverse proxy not accessible

### ISSUE THREAD

**Issue by busyboy77** [maximemoreillon/chartmuseum-gui#1]
the application doesn't work behind nginx reverse proxy. here is my nginx snippet.

```YAML
    location /gui/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://gui:3000/;
        proxy_redirect off;
    }
```

and my docker-compose.yaml is 

```YAML
services:
  gui:
    image: moreillon/chartmuseum-gui:latest
    environment:
      PUBLIC_CHARTMUSEUM_URL: http://charter:8080
#    ports:
#      - 3000:3000
    networks:
      - charter
  nginx:
    image: bitnami/nginx:1.23
    ports:
      - '80:8080'
    volumes:
      - /root/helmmeusum/charter.conf:/opt/bitnami/nginx/conf/server_blocks/charter.conf:ro
    networks:
      - charter
```

any idea what we need to implement 

however the application responds to `curl http://gui:3000/ ` request inside the nginx container.

**Comment by maximemoreillon** [comment]
Hello @busyboy77 ,

Thanks so much for giving this application a try!

Sorry to hear you har having trouble with it. I haven't tried it behind a reverse-proxy so I am unsure of how to make it work, but I will try to find a solution.

Please do keep in mind that I might not have enough time to solve this issue rapidly.

Best regards

**Comment by maximemoreillon** [comment]
I found some time today to work on this issue and might have found a solution.

Would you mind pulling the [latest container image](https://hub.docker.com/layers/moreillon/chartmuseum-gui/3786d02d/images/sha256-a1053305c9bc8a638d6dbf07ce22bd466d8d88ca64915779d08bb43fb23b8560?context=repo) and try setting the PATH_BASE environment variable to '/gui' ?

**Comment by busyboy77** [comment]
[Hi]

Thanks  for your help. below are the logs from Gui


```
helmmeusum-gui-1      | TypeError: fetch failed
helmmeusum-gui-1      |     at fetch (file:///app/build/shims.js:20794:14)
helmmeusum-gui-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
helmmeusum-gui-1      |     at async Object.fetch (file:///app/build/server/index.js:3487:12)
helmmeusum-gui-1      |     at async load (file:///app/build/server/chunks/3-1c7f2ccc.js:4:15)
helmmeusum-gui-1      |     at async load_server_data (file:///app/build/server/index.js:1797:18)
helmmeusum-gui-1      |     at async Promise.all (index 1)
helmmeusum-gui-1      |     at async render_data (file:///app/build/server/index.js:2941:19)
helmmeusum-gui-1      |     at async resolve (file:///app/build/server/index.js:3812:22)
helmmeusum-gui-1      |     at async respond (file:///app/build/server/index.js:3715:22)
helmmeusum-gui-1      |     at async Array.ssr (file:///app/build/handler.js:1190:3)
```

with docker-compose.yaml as below

```YAML
services:
  gui:
#    image: moreillon/chartmuseum-gui:latest
    image: moreillon/chartmuseum-gui:3786d02d
    environment:
      PUBLIC_CHARTMUSEUM_URL: http://charter:8080
      PATH_BASE: "/gui"
    ports:
      - 3000:3000
    networks:
      - charter
  nginx:
    image: bitnami/nginx:1.23
    ports:
      - '80:8080'
    volumes:
      - /root/helmmeusum/charter.conf:/opt/bitnami/nginx/conf/server_blocks/charter.conf:ro
    networks:
      - charter
```

and nginx logs say something like this.

```
/smui.css HTTP/1.1", upstream: "http://172.22.0.6:8080/smui.css", host: "charts.dummy.com", referrer: "http://charts.dummy.com/gui/"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /smui.css HTTP/1.1" 502  552 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /chartmuseum.png HTTP/1.1" 502  552 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 2023/04/10 11:34:49 [error] 41#41: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.11, server: charts.dummy.com, request: "GET /chartmuseum.png HTTP/1.1", upstream: "http://172.22.0.6:8080/chartmuseum.png", host: "charts.dummy.com", referrer: "http://charts.dummy.com/gui/"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/0.e9e886f9.js HTTP/1.1" 200  109 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/1.90805fc9.js HTTP/1.1" 200  107 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/stores.f902bb08.js HTTP/1.1" 200  178 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/entry/error.svelte.52155717.js HTTP/1.1" 200  515 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/2.4c5bc7a3.js HTTP/1.1" 200  107 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/chartmuseum.png HTTP/1.1" 200  67386 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/Ripple.eee4c8ac.js HTTP/1.1" 200  15457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/chunks/3.8266fb32.js HTTP/1.1" 200  112 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/entry/charts-page.svelte.f495dca4.js HTTP/1.1" 200  23296 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/smui-dark.css HTTP/1.1" 200  39161 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/smui.css HTTP/1.1" 200  40922 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/immutable/assets/_page.8e7d21f5.css HTTP/1.1" 200  181 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/charts/__data.json?x-sveltekit-invalidated=_1 HTTP/1.1" 200  96 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
helmmeusum-nginx-1    | 192.168.50.11 - - [10/Apr/2023:11:34:49 +0000] "GET /gui/_app/version.json HTTP/1.1" 200  27 "http://charts.dummy.com/gui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"
```
